In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
print("Libraries loaded successfully!")

Libraries loaded successfully!

In [2]:
engine = create_engine(
    "postgresql://postgres:admin123@localhost:5432/health_db"
)
print("Connected to database!")

Connected to database!

In [5]:
df = pd.read_csv(r"C:\Users\hanna\Downloads\diabetes+130-us+hospitals+for+years+1999-2008\diabetic_data.csv")
print(f"Rows: {len(df)}")
print(f"Columns: {len(df.columns)}")
df.head()

Rows: 101766
Columns: 50

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [7]:
engine = create_engine(
    "postgresql://postgres:admin123@localhost:5432/health_db"
)
print("Reconnected!")

Reconnected!

In [9]:
from sqlalchemy import create_engine
engine = create_engine(
    "postgresql://postgres:admin123@localhost:5432/health_db"
)
print("Connected!")

Connected!

In [10]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\hanna\Downloads\diabetes+130-us+hospitals+for+years+1999-2008\diabetic_data.csv")
df.replace("?", np.nan, inplace=True)
print(f"Data ready! {len(df)} rows")

Data ready! 101766 rows

In [12]:
import psycopg2

try:
    conn = psycopg2.connect(
        host="localhost",
        database="health_db", 
        user="postgres",
        password="admin123",
        port="5432"
    )
    print("PostgreSQL is running!")
    conn.close()
except Exception as e:
    print(f"Error: {e}")

Error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "health_db" does not exist

In [13]:
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

# Connect to default postgres database
conn = psycopg2.connect(
    host="localhost",
    database="postgres", 
    user="postgres",
    password="admin123",
    port="5432"
)
conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
cursor = conn.cursor()

# Create health_db
cursor.execute("CREATE DATABASE health_db")
print("Database health_db created successfully!")

cursor.close()
conn.close()

Database health_db created successfully!

In [14]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:admin123@localhost:5432/health_db"
)

df.to_sql("patient_visits", engine, 
          if_exists="replace", index=False)

print(f"SUCCESS! {len(df)} patient records loaded!")

SUCCESS! 101766 patient records loaded!

In [15]:
# Verify data is in database
import pandas as pd
df_check = pd.read_sql("SELECT COUNT(*) as total_patients FROM patient_visits", engine)
print(df_check)

# Preview first 5 rows from database
df_preview = pd.read_sql("SELECT * FROM patient_visits LIMIT 5", engine)
df_preview

   total_patients
0          101766

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),None,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),None,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),None,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),None,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),None,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO